version: '3.9'

name: db-local-learner

services:
  db-local-learner:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=local
      - POSTGRES_HOST_AUTH_METHOD=trust
